# Generated by Django 4.2.24 on 2025-10-01 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('investment', 'Investment'), ('crypto', 'Crypto'), ('bond', 'Bond'), ('loan', 'Loan'), ('other', 'Other')], default='cash', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD - United States Dollar'), ('EUR', 'EUR - Euro'), ('JPY', 'JPY - Japanese Yen'), ('GBP', 'GBP - British Pound Sterling'), ('AUD', 'AUD - Australian Dollar'), ('CAD', 'CAD - Canadian Dollar'), ('CHF', 'CHF - Swiss Franc'), ('CNY', 'CNY - Chinese Yuan'), ('SEK', 'SEK - Swedish Krona'), ('NZD', 'NZD - New Zealand Dollar'), ('HKD', 'HKD - Hong Kong Dollar')], default='USD', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('account', 'date')},
            },
        ),
    ]
