# Generated by Django 4.2.24 on 2025-10-01 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('base_currency', 'target_currency')},
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=30, null=True)),
                ('asset_type', models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Cryptocurrency'), ('real_estate', 'Real Estate'), ('cash', 'Cash')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Cost per unit at time of purchase', max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('previous_market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
