# Generated by Django 5.2.6 on 2025-09-12 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('HKD', 'HKD'), ('RMB', 'RMB'), ('CAD', 'CAD')], max_length=3)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('food', 'Food'), ('transportation', 'Transportation'), ('salary', 'Salary'), ('utilities', 'Utilities'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
