# Generated by Django 5.2.6 on 2025-09-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], default='cash', max_length=20),
        ),
    ]
