# Generated by Django 5.2.6 on 2025-09-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_account_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
