# Generated by Django 5.2.6 on 2025-09-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_asset_change_asset_market_price_asset_market_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('HKD', 'HKD'), ('RMB', 'RMB'), ('CAD', 'CAD')], default='USD', max_length=3),
        ),
    ]
