# Generated by Django 5.2.6 on 2025-09-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_account_balance_account_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('housing', 'Housing'), ('transportation', 'Transportation'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('utilities', 'Utilities'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('other_expense', 'Other Expense')], max_length=20),
        ),
    ]
