# Generated by Django 5.2.6 on 2025-09-21 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('HKD', 'HKD'), ('RMB', 'RMB'), ('CAD', 'CAD'), ('CNY', 'CNY')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_for_account', to='transactions.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('HKD', 'HKD'), ('RMB', 'RMB'), ('CAD', 'CAD'), ('CNY', 'CNY')], max_length=3),
        ),
    ]
