# Generated by Django 5.2.6 on 2025-09-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_account_currency_alter_transaction_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('credit_card', 'Credit Card'), ('investment', 'Investment'), ('loan', 'Loan'), ('other', 'Other')], default='bank', max_length=20),
        ),
    ]
