# Generated by Django 5.2.6 on 2025-09-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
