# Generated by Django 5.2.6 on 2025-09-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_asset_symbol_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD - United States Dollar'), ('EUR', 'EUR - Euro'), ('JPY', 'JPY - Japanese Yen'), ('GBP', 'GBP - British Pound Sterling'), ('AUD', 'AUD - Australian Dollar'), ('CAD', 'CAD - Canadian Dollar'), ('CHF', 'CHF - Swiss Franc'), ('CNY', 'CNY - Chinese Yuan'), ('SEK', 'SEK - Swedish Krona'), ('NZD', 'NZD - New Zealand Dollar'), ('HKD', 'HKD - Hong Kong Dollar')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('investment', 'Investment'), ('food', 'Food'), ('transportation', 'Transportation'), ('housing', 'Housing'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('education', 'Education'), ('shopping', 'Shopping'), ('other', 'Other'), ('other_expense', 'Other Expense')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD - United States Dollar'), ('EUR', 'EUR - Euro'), ('JPY', 'JPY - Japanese Yen'), ('GBP', 'GBP - British Pound Sterling'), ('AUD', 'AUD - Australian Dollar'), ('CAD', 'CAD - Canadian Dollar'), ('CHF', 'CHF - Swiss Franc'), ('CNY', 'CNY - Chinese Yuan'), ('SEK', 'SEK - Swedish Krona'), ('NZD', 'NZD - New Zealand Dollar'), ('HKD', 'HKD - Hong Kong Dollar')], max_length=3),
        ),
    ]
