# Generated by Django 4.2.24 on 2025-09-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_balancesnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('credit_card', 'Credit Card'), ('investment', 'Investment'), ('crypto', 'Crypto'), ('bond', 'Bond'), ('loan', 'Loan'), ('other', 'Other')], default='bank', max_length=20),
        ),
    ]
