# Generated by Django 4.2.24 on 2025-09-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('CNY', 'CNY'), ('SEK', 'SEK'), ('NZD', 'NZD'), ('HKD', 'HKD'), ('RMB', 'RMB')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('CNY', 'CNY'), ('SEK', 'SEK'), ('NZD', 'NZD'), ('HKD', 'HKD'), ('RMB', 'RMB')], max_length=3),
        ),
    ]
