# Generated by Django 4.2.24 on 2025-09-29 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_account_account_type'),
        ('transactions', '0012_exchangerate'),
    ]

    operations = [
    ]
