# Generated by Django 4.2.24 on 2025-09-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_migrate_bank_to_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='previous_market_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('investment', 'Investment'), ('crypto', 'Crypto'), ('bond', 'Bond'), ('loan', 'Loan'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
