# Generated by Django 4.2.24 on 2025-10-01 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0015_asset_previous_market_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='account',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='balancesnapshot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='balancesnapshot',
            name='account',
        ),
        migrations.RemoveField(
            model_name='balancesnapshot',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_for_account', to='accounts.account'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='BalanceSnapshot',
        ),
    ]
