# Generated by Django 4.2.24 on 2025-10-04 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0016_remove_account_user_remove_asset_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('investment', 'Investment'), ('food', 'Food'), ('transportation', 'Transportation'), ('housing', 'Housing'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('education', 'Education'), ('shopping', 'Shopping'), ('other', 'Other'), ('other_expense', 'Other Expense')], max_length=20)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD - United States Dollar'), ('EUR', 'EUR - Euro'), ('JPY', 'JPY - Japanese Yen'), ('GBP', 'GBP - British Pound Sterling'), ('AUD', 'AUD - Australian Dollar'), ('CAD', 'CAD - Canadian Dollar'), ('CHF', 'CHF - Swiss Franc'), ('CNY', 'CNY - Chinese Yuan'), ('SEK', 'SEK - Swedish Krona'), ('NZD', 'NZD - New Zealand Dollar'), ('HKD', 'HKD - Hong Kong Dollar')], max_length=3)),
                ('period', models.CharField(choices=[('Month', 'Month'), ('Year', 'Year')], max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
